spring:
  application:
    name: orderserver81
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///order
    username: root
    password: 123123
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  type-aliases-package: sx.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true

server:
  port: 8081
logging:
    level:
      com.sx: debug

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka